spring:
  datasource:
    # mysql
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  # jpa
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none

  messages:
    basename: i18n/exception
    encoding: UTF-8

  # 파일 업로드 크기 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # redis
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOSTNAME}

logging.level:
  org.hibernate.SQL: info

jwt:
  secret: ${JWT_SECRET_KEY}